fixed code

diff --git a/latte b/latte
--- a/latte
+++ b/latte
@@ -42,6 +42,98 @@ install_package() {
 
     echo "Installing $NAME $VERSION..."
 
+    tar --transform='s|^\.|/|' --show-transformed-names --exclude='metadata.txt' -xzvf "$pkg_archive" -C "$TARGET_ROOT" | grep -v '/$' > "$MANIFEST_DIR/$NAME.list"
+
+    if ! grep -q "^$NAME " "$DB_FILE"; then
+        echo "$NAME $VERSION" >> "$DB_FILE"
+    fi
+
+    echo "Successfully installed $NAME $VERSION"
+}
+
+remove_package() {
+    local pkg_name="$1"
+
+    if ! grep -q "^$pkg_name " "$DB_FILE"; then
+        echo "Error: Package '$pkg_name' is not installed."
+        exit 1
+    fi
+
+    echo "Removing $pkg_name"
+    echo "Removed $pkg_name"
+
+    local manifest="$MANIFEST_DIR/$pkg_name.list"
+    if [ -f "$manifest" ]; then
+        while read -r file; do
+            local target_path="${TARGET_ROOT%/}/$file"
+            
+            if [ -n "$file" ] && [ -f "$target_path" ]; then
+                rm -f "$target_path"
+            elif [ -n "$file" ] && [ -d "$target_path" ]; then
+                rmdir "$target_path" 2>/dev/null
+            fi
+        done < <(tac "$manifest")
+        
+        rm -f "$manifest"
+    fi
+
+    sed -i "/^$pkg_name /d" "$DB_FILE"
+    echo "Successfully removed $pkg_name."
+}
+
+list_packages() {
+    cat $DB_FILE
+}
+
+latte_version() {
+    echo "Latte v1.0 stable | Capuccino"
+}
+
+build_package() {
+    local inputdir="${1%/}"
+    local outputdir="${2%/}"
+
+    mkdir -p "$outputdir"
+    local final_archive="$outputdir.latte"
+
+    echo "Packaging bundle from '$inputdir'..."
+    
+    if tar -czf "$final_archive" -C "$inputdir" .; then
+        echo "Successfully built package: $final_archive"
+        return 0
+    else
+        echo "Error: Failed to create .latte package."
+        return 1
+    fi
+}
+
+
+if [ "$1" == "install" ]; then
+    install_package "$2"
+elif [ "$1" == "list" ]; then
+    list_packages
+elif [ "$1" == "remove" ]; then
+    remove_package "$2"
+elif [ "$1" == "version" ]; then
+    latte_version
+elif [ "$1" == "build" ]; then
+    build_package "$2" "$3"
+else
+    echo "Usage:
+    latte install <package.latte>
+    latte list
+    latte remove <package>
+    latte version
+    latte build <input_directory> <output_directory>"
+fi
+
+    [[ -z "$NAME" || -z "$VERSION" ]] && { echo "Error: NAME or VERSION missing in metadata.txt"; exit 1; }
+    [[ "$NAME" =~ ^[a-zA-Z0-9._-]+$ ]] || { echo "Error: Invalid NAME (only alphanumeric, ., , - allowed)"; exit 1; }
+    [[ "$VERSION" =~ ^[a-zA-Z0-9.-]+$ ]] || { echo "Error: Invalid VERSION (only alphanumeric, ., _, - allowed)"; exit 1; }
+    rm -rf "$tmp_dir"
+
+    echo "Installing $NAME $VERSION..."
+
     tar --transform --exclude='metadata.txt' -xzvf "$pkg_archive" -C "$TARGET_ROOT" | grep -v '/$' > "$MANIFEST_DIR/$NAME.list"
 
     if ! grep -q "^$NAME " "$DB_FILE"; then
